config/routes.rb
Rails.application.routes.draw do
  resources :process_trainings
  resources :trainings
  resources :exercises
  devise_for :users
  devise_for :coaches
  resources :users, :coaches, only: [:show, :edit, :update, :index] do
    get 'chart', on: :member
    get 'dasboards', on: :collection
    get 'statistics', on: :member

    resources :personal_characteristics
  end
  resources :groups do
    resources :schedules

  end
  resources :products
  resources :rations 
 
  get 'add_to' => 'rations#add_to'
  delete 'delete' => 'rations#delete'
  get 'add_to/training' => 'trainings#add_to'
  delete 'delete/training' => 'trainings#delete'
  root 'static_pages#home'
 


  
  get "hello" => "static_pages#dasboard"
  

end

app/models/ration.rb
class Ration < ActiveRecord::Base
  has_and_belongs_to_many :products
  has_many :users
end

app/models/training.rb
class Training < ActiveRecord::Base
  has_and_belongs_to_many :exercises
  has_many :process_trainings
  has_many :users

  validates :number, :name, :notice, presence: true
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :set_training, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_coach!

  authorize_resource
  # GET /trainings
  # GET /trainings.json
  def index
    @trainings = Training.all.paginate(page: params[:page], per_page: 3)
  end

  # GET /trainings/1
  # GET /trainings/1.json
  def show
  end

  # GET /trainings/new
  def new
    @exercise = Exercise.all.map{ |c| [c.name, c.id]}
    @training = Training.new
  end

  # GET /trainings/1/edit
  def edit
  end

  # POST /trainings
  # POST /trainings.json
  def create
    @exercise = Exercise.all.map{ |c| [c.name, c.id]}
    @training = Training.new(training_params)

    respond_to do |format|
      if @training.save
        format.html { redirect_to @training, notice: 'Training was successfully created.' }
        format.json { render :show, status: :created, location: @training }
      else
        format.html { render :new }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_to
    render layout: false
    
  end

  # PATCH/PUT /trainings/1
  # PATCH/PUT /trainings/1.json
  def update
    respond_to do |format|
      if @training.update(training_params)
        format.html { redirect_to @training, notice: 'Training was successfully updated.' }
        format.json { render :show, status: :ok, location: @training }
      else
        format.html { render :edit }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    @training.destroy
    respond_to do |format|
      format.html { redirect_to trainings_url, notice: 'Training was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = Training.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def training_params
      params.require(:training).permit(:name, :number, :notice).tap do |whitelisted|
        whitelisted[:exercise_param] = params[:training][:exercise_param]
        whitelisted[:exercise_param_f] = params[:training][:exercise_param_f]
        whitelisted[:exercise_param_s] = params[:training][:exercise_param_s]
        whitelisted[:exercise_param_t] = params[:training][:exercise_param_t]
        whitelisted[:exercise_param_fr] = params[:training][:exercise_param_fr]
        whitelisted[:exercise_param_fv] = params[:training][:exercise_param_fv]
        whitelisted[:exercise_param_sx] = params[:training][:exercise_param_sx]
        whitelisted[:exercise_param_sv] = params[:training][:exercise_param_sv]
        whitelisted[:exercise_param_cardio] = params[:training][:exercise_param_cardio]
        
      end
    end
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_form.html.erb
<%= simple_form_for(@training) do |f| %>
  <%= f.error_notification %>

  <div class="row">
   <div class="col-md-10">
  <%= f.input :number, label: "Номер" %>
  <%= f.input :name, label: "Название" %>
  <%= f.input :notice, label: "Заметки" %>
  <div class="full_training" style="display:none">
  <div class="col-md-4">
  <%= f.simple_fields_for :exercise_param do |setting| %>
       
        <%= setting.select(:training_id, options_for_select(@exercise), :prompt => "Выберите упражнение") %>
        <%= setting.input :count, label: "Колличество повтор", :input_html => { :type => "number", min: '1' }%>
        <%= setting.input :number, label: "Колличество подходов", :input_html => { :type => "number", min: '1' }%>
        <%= setting.input :weight, label: "Вес снаряда (кг)", :input_html => { :type => "number", min: '1' }%>
     
   <% end %>     
  
</div>
 <div class="col-md-4">
  <%= f.simple_fields_for :exercise_param_f do |setting| %>
       
        <%= setting.select(:training_id, options_for_select(@exercise), :prompt => "Выберите упражнение") %>
        <%= setting.input :count, label: "Колличество повтор", :input_html => { :type => "number", min: '1' }%>
        <%= setting.input :number, label: "Колличество подходов", :input_html => { :type => "number", min: '1' }%>
        <%= setting.input :weight, label: "Вес снаряда (кг)", :input_html => { :type => "number", min: '1' }%>
     
   <% end %>     
  
</div>
 <div class="col-md-4">
  <%= f.simple_fields_for :exercise_param_s do |setting| %>
       
        <%= setting.select(:training_id, options_for_select(@exercise), :prompt => "Выберите упражнение") %>
        <%= setting.input :count, label: "Колличество повтор", :input_html => { :type => "number", min: '1' }%>
        <%= setting.input :number, label: "Колличество подходов", :input_html => { :type => "number", min: '1' }%>
        <%= setting.input :weight, label: "Вес снаряда (кг)", :input_html => { :type => "number", min: '1' }%>
     
   <% end %>     
  
</div>
 <div class="col-md-4">
  <%= f.simple_fields_for :exercise_param_t do |setting| %>
       
        <%= setting.select(:training_id, options_for_select(@exercise), :prompt => "Выберите упражнение") %>
        <%= setting.input :count, label: "Колличество повтор", :input_html => { :type => "number", min: '1' }%>
        <%= setting.input :number, label: "Колличество подходов", :input_html => { :type => "number", min: '1' }%>
        <%= setting.input :weight, label: "Вес снаряда (кг)", :input_html => { :type => "number", min: '1' }%>
     
   <% end %>     
  
</div>
 <div class="col-md-4">
  <%= f.simple_fields_for :exercise_param_fr do |setting| %>
       
        <%= setting.select(:training_id, options_for_select(@exercise), :prompt => "Выберите упражнение") %>
        <%= setting.input :count, label: "Колличество повтор", :input_html => { :type => "number", min: '1' }%>
        <%= setting.input :number, label: "Колличество подходов", :input_html => { :type => "number", min: '1' }%>
        <%= setting.input :weight, label: "Вес снаряда (кг)", :input_html => { :type => "number", min: '1' }%>
     
   <% end %>     
  
</div>
 <div class="col-md-4">
  <%= f.simple_fields_for :exercise_param_fv do |setting| %>
       
        <%= setting.select(:training_id, options_for_select(@exercise), :prompt => "Выберите упражнение") %>
        <%= setting.input :count, label: "Колличество повтор", :input_html => { :type => "number", min: '1' }%>
        <%= setting.input :number, label: "Колличество подходов", :input_html => { :type => "number", min: '1' }%>
        <%= setting.input :weight, label: "Вес снаряда (кг)", :input_html => { :type => "number", min: '1' }%>
     
   <% end %>     
  
</div>
</div>
<div class="col-md-9 col-sm-offset-2">
<div class="cardio" style="display:none">
  <%= f.simple_fields_for :exercise_param_cardio do |setting| %>
       
        <%= setting.input(:type,  collection: [ "Беговая дорожка", "Велотренажор", "Бег трусцой / (вокруг стадиона)"], prompt: "Выберите тип кардио упражнение", label: "Тип")%>
        <%= setting.input :time, label: "Время выполнения (в минутах)", :input_html => { :type => "number", min: '1' }%>
        <%= setting.input :quantaty, label: "Максимальная частота пульса при выполнения", :input_html => { :type => "number", min: '1' }%>
        
     
   <% end %>     
  
</div>
</div>
</div>
 <div class="col-md-2">
<div class="inter">
  <div class="form-actions">
    <%= f.button :submit, "Создать тренировку", :class => 'btn btn-success btn-block' %>
  </div><br>
<% end %>
 <div><%= link_to "Кардио упражнения", "#" , :class => 'btn btn-primary btn-block', id: "cardios" %></div><br>
  <div><%= link_to "Силовые упражнения", "#" , :class => 'btn btn-primary btn-block', id: "full_train" %></div><br>
  </div>
  </div>
  </div>

app/views/trainings/add_to.html.erb
 <div class= 'lol'>
 <div class="col-md-4">
 <div class="test">
  <h4>Продукты на дополнительный прием</h4>
   <%= collection_check_boxes(:new, :product_ids, Exercise.all, :id, :name)do |b| %>
    <div class="row">
      <%= b.label(class: "check_box") do %>
        <div class="col-xs-8">
          <%= b.check_box(class: "check_box") %>
        </div>

        <div class="col-xs-10">
          <%= b.object.name %>
        </div>       
      <% end %>
    </div>
  <% end %>

  </div>
  </div>
</div>

app/views/trainings/edit.html.erb
 <div class="col-md-10 col-md-offset-1">
<h1>Редактировать тренировку</h1>

<%= render 'form' %>

</div>

app/views/trainings/index.html.erb
<table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Номер</th>
        <th>Название</th>
        <th>Описание</th>
        <th>Просмотр рациона</th>
        <th>Удаление рациона</th>
      </tr>
    </thead>
  <tbody>
  <% @trainings.each do |f| %>
    <tr>
      <td><h4><%= f.number %></h4></td>
      <td><h4><%= f.name %></h4></td>
      <td><h4><%= f.notice %></h4></td>
      <td><%= link_to "Просмотреть", f, class: "btn btn-info" %></td>
      <td><%= button_to "Удалить", f, method: :delete, class: "btn btn-danger" %></td>
    </tr>
  </tbody>
<% end %>
</table>
<div class="container text-center">
  <div class="pagination">
    <%= will_paginate @trainings, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/trainings/new.html.erb
 <div class="col-md-10 col-md-offset-1">
<h1>Новая тренировка</h1>

<%= render 'form' %>

</div>

app/views/trainings/show.html.erb
<div class="row">
<div class="col-md-12">
<h3>Номер тренировки: <%= @training.number %></h3>
<h4>Названия: <%= @training.name %></h3></h4> 
<h4>Заметки: <%= @training.notice %></h3></h4>
<div class="border"> 
<div class="col-md-3">
<% if @training.exercise_param['training_id'] != ""%>
    <h4>Название упражнения: <%= link_to "#{Exercise.find(@training.exercise_param['training_id'].to_i).name}", exercise_path(Exercise.find(@training.exercise_param['training_id'].to_i)) if @training.exercise_param['training_id']%></h4>
    <h4>Колличесво подходов: <%=@training.exercise_param['count']%></h4>
    <h4>Колличесво повторов: <%= @training.exercise_param['number'] %></h4>
    <h4>Вес снаряда: <%=  @training.exercise_param['weight'] %>  </h4>
<% end %>

</div>
<div class="col-md-3">
<% if @training.exercise_param_f['training_id'] != "" %>
    <h4>Название упражнения: <%= link_to "#{Exercise.find(@training.exercise_param_f['training_id'].to_i).name}", exercise_path(Exercise.find(@training.exercise_param_f['training_id'].to_i)) if @training.exercise_param_f['training_id']%></h4>
    <h4>Колличесво подходов: <%=@training.exercise_param_f['count']%></h4>
    <h4>Колличесво повторов: <%= @training.exercise_param_f['number'] %></h4>
    <h4>Вес снаряда: <%=  @training.exercise_param_f['weight'] %>  </h4>
<% end %>

</div>
<div class="col-md-3">
<% if @training.exercise_param_s['training_id'] != ""%>
    <h4>Название упражнения: <%= link_to "#{Exercise.find(@training.exercise_param_s['training_id'].to_i).name}", exercise_path(Exercise.find(@training.exercise_param_s['training_id'].to_i)) if @training.exercise_param_s['training_id']%></h4>
    <h4>Колличесво подходов: <%=@training.exercise_param_s['count']%></h4>
    <h4>Колличесво повторов: <%= @training.exercise_param_s['number'] %></h4>
    <h4>Вес снаряда: <%=  @training.exercise_param_s['weight'] %>  </h4>
<% end %>

</div>
<div class="col-md-3">
<% if @training.exercise_param_t['training_id'] != ""%>
    <h4>Название упражнения: <%= link_to "#{Exercise.find(@training.exercise_param_t['training_id'].to_i).name}", exercise_path(Exercise.find(@training.exercise_param_t['training_id'].to_i)) if @training.exercise_param_t['training_id'] %></h4>
    <h4>Колличесво подходов: <%=@training.exercise_param_t['count']%></h4>
    <h4>Колличесво повторов: <%= @training.exercise_param_t['number'] %></h4>
    <h4>Вес снаряда: <%=  @training.exercise_param_t['weight'] %>  </h4>
<% end %>

</div>
<div class="col-md-3">
<% if @training.exercise_param_fr['training_id'] != ""%>
    <h4>Название упражнения: <%= link_to "#{Exercise.find(@training.exercise_param_fr['training_id'].to_i).name}", exercise_path(Exercise.find(@training.exercise_param_fr['training_id'].to_i)) if @training.exercise_param_fr['training_id']%></h4>
    <h4>Колличесво подходов: <%=@training.exercise_param_fr['count']%></h4>
    <h4>Колличесво повторов: <%= @training.exercise_param_fr['number'] %></h4>
    <h4>Вес снаряда: <%=  @training.exercise_param_fr['weight'] %>  </h4>
<% end %>

</div>
<div class="col-md-3">
<% if @training.exercise_param_fv['training_id']!= "" %>
    <h4>Название упражнения: <%= link_to "#{Exercise.find(@training.exercise_param_fv['training_id'].to_i).name}", exercise_path(Exercise.find(@training.exercise_param_fv['training_id'].to_i)) if @training.exercise_param_fv['training_id']%></h4>
    <h4>Колличесво подходов: <%=@training.exercise_param_fv['count']%></h4>
    <h4>Колличесво повторов: <%= @training.exercise_param_fv['number'] %></h4>
    <h4>Вес снаряда: <%=  @training.exercise_param_fv['weight'] %>  </h4>
<% end %>

</div>

<div class="col-md-6">
<% if @training.exercise_param_cardio %>

    <h4>Тип кардио-упражнения: <%=@training.exercise_param_cardio['type']%></h4>
    <h4>Время выполнения: <%= @training.exercise_param_cardio['time'] %></h4>
    <h4>Максимальная частота пульса <%=  @training.exercise_param_cardio['quantaty'] %>  </h4>
<% end %>

</div>
</div>
</div>
</div>