config/routes.rb
Rails.application.routes.draw do
  resources :process_trainings
  resources :trainings
  resources :exercises
  devise_for :users
  devise_for :coaches
  resources :users, :coaches, only: [:show, :edit, :update, :index] do
    get 'chart', on: :member
    get 'dasboards', on: :collection
    get 'statistics', on: :member

    resources :personal_characteristics
  end
  resources :groups do
    resources :schedules

  end
  resources :products
  resources :rations 
 
  get 'add_to' => 'rations#add_to'
  delete 'delete' => 'rations#delete'
  get 'add_to/training' => 'trainings#add_to'
  delete 'delete/training' => 'trainings#delete'
  root 'static_pages#home'
 


  
  get "hello" => "static_pages#dasboard"
  

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :users
  belongs_to :coach
  has_many :schedules

  validates :title, :data_start, :data_finish, :days, presence: true

  RUFE_INDEX = ["Хорошо", "Нормально", "Удовлетворительно", "Плохо"]
  WEIGHT_INDEX = ["Анорексия", "Дефицит_массы_тела", "Норма", "Избыток_массы_тела",  "Первая_стадия_ожирения", "Вторая_стадия_ожирения", "Третья_стадия_ожирения" ]
  DAYS = ["Понедельник, Среда, Пятница", "Вторник, Четверг, Суббота", "Понедельник, Четверг, Суббота", "Вторник, Четверг, Суббота"]
 
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :coaches_load, only: [:new, :create]
  before_action :find_group, only: [:show, :destroy]
  authorize_resource
  def new 
    @group = Group.new
  end 

  def show
  end

  def create
    @group = Group.new(groups_params)
    @group.coach_id = params[:coach_id]
    if @group.save
      redirect_to @group
    else
      render :new
    end
  end
  def index
    @groups = Group.all
  end
  def destroy
    @group.destroy
    redirect_to groups_path
  end
  

    

  
  private

    def groups_params
      params.require(:group).permit(:title, :coach_id, :data_start, :data_finish, :days)
    end

    def coaches_load
      coaches = User.where(type: "Coach")
      @coaches = coaches.find_each.map{ |c| [c.email, c.id]} 
    end

    def find_group
      @group = Group.find(params[:id])
    end


end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/index.html.erb
<table class="table table-bordered table-striped">
      <tr>
        <th class="text-center">№</th>
        <th class="text-center">Название</th>
        <th class="text-center">Дата создания </th>
        <th class="text-center">Колличесво работников<br> в группе</th>
        <th class="text-center">Удаление группы</th>
      </tr>
<% @groups.each do |f| %>
  <tr>
    <td class="text-center"></td>
    <td><h4><%= link_to "#{f.title}", group_path(f) %></h4></td>
    <td><h4 class="text-center"><%= f.created_at.strftime("%d-%m-%Y") %></h4></td>
    <td><h4 class="text-center"><%= f.users.count %></h4></td>
    <td><h4 class="text-center"><%= button_to "Удалить группу", f, method: :delete, class: "btn btn-danger" %></h4></td>
  </tr>
<% end %>
</table>

<script>
  $('.table tr').each(function(i) {
    i && $(this).find('td:first').text(i);

  });
</script>

app/views/groups/new.html.erb
<%= simple_form_for( @group) do |f|%>
    <%= f.error_notification %>
      <div class="col-md-6 col-md-offset-3">
          <div class="new-point">
            <%= f.input :title, label: "Название" %>
          <%= f.simple_fields_for :groups_params do |setting| %>
            <%= setting.input :rufe, label: "Формировать по индексу Руфье", collection: Group::RUFE_INDEX, prompt: "Выберите ваше значение", as: :select %>  
            <%= setting.input :weight, label: "Формировать по индексу массы тела", collection: Group::WEIGHT_INDEX, prompt: "Выберите ваше значение", as: :select %>
        <% end %>
        <%= f.input :days, label: "Дни занятия", collection: Group::DAYS, prompt: "Выберите ваше значение", as: :select %>
        <%= f.input :coach_id, label: "Тренер", collection: @coaches, :prompt => "Выберите тренера" %>
        <h4>Дата начало занятий группы</h4>
        <%= f.date_field :data_start%>
        <h4>Дата окончаний занятий группы</h4>
            <%= f.date_field :data_finish, as: :date, label: "Дата окончаний занятий группы" %>
          </div><br>
    <div class="group">
      <%= f.button :submit, "Создать новую группу", class: "btn btn-success" %>
    </div>
  <% end %>

app/views/groups/show.html.erb
<h3>Название: <%= @group.title %> </h3>
<h4>Дни занятий: <%= @group.days %> </h4>
<h4>Начало занятий в группе: <%= @group.data_start %> </h4>
<h4>Окончание занятий в группе: <%= @group.data_finish %> </h4>
<table class="table table-bordered table-striped">
      <tr>
        <th>№</th>
        <th>Фамилия</th>
        <th>Имя</th>
        <th>Должность</th>
        <th>Пол</th>
      </tr>
<% @group.users.each do |user|  %>
  <tr>
    <td></td>
    <td><h4><%= link_to "#{user.last_name}", user_path(user) %></td>
    <td><h4><%= user.first_name %></h4></td>
    <td><h4><%= user.position %></h4></td>
    <td><h4><%= user.gender %></h4></td>
  </tr>
<% end %>
</table>
<%= link_to "Новое занятие", new_group_schedule_path(@group), class: "btn btn-info" %>

<script>
  $('.table tr').each(function(i) {
    i && $(this).find('td:first').text(i);

  });
</script>