config/routes.rb
Rails.application.routes.draw do
  resources :process_trainings
  resources :trainings
  resources :exercises
  devise_for :users
  devise_for :coaches
  resources :users, :coaches, only: [:show, :edit, :update, :index] do
    get 'chart', on: :member
    get 'dasboards', on: :collection
    get 'statistics', on: :member

    resources :personal_characteristics
  end
  resources :groups do
    resources :schedules

  end
  resources :products
  resources :rations 
 
  get 'add_to' => 'rations#add_to'
  delete 'delete' => 'rations#delete'
  get 'add_to/training' => 'trainings#add_to'
  delete 'delete/training' => 'trainings#delete'
  root 'static_pages#home'
 


  
  get "hello" => "static_pages#dasboard"
  

end

app/models/ration.rb
class Ration < ActiveRecord::Base
  has_and_belongs_to_many :products
  has_many :users
end

app/controllers/rations_controller.rb
class RationsController < ApplicationController

  before_action :find_ration, only: [:show, :destroy, :edit, :update]

  def new 
    @ration = Ration.new
  end 

  def show
    @morning = find_product(@ration.morning.compact)
    @afternoon = find_product(@ration.afternoon.compact)
    @lunch = find_product(@ration.lunch.compact)
    @evening = find_product(@ration.evening.compact)
    @new_ration = find_product(@ration.new_ration.compact)
  end

  def etit
  end

  def update
    @morning = params[:morning][:product_ids]
    @afternoon = params[:afternoon][:product_ids]
    @lunch = params[:lunch][:product_ids]
    @evening = params[:evening][:product_ids]
    if params[:new_ration].blank?
      @new_ration = []
    else
      @new_ration = params[:new_ration][:product_ids]
    end
    @ration.update(rations_params.merge(morning: @morning, afternoon: @afternoon, lunch: @lunch, evening: @evening, new_ration: @new_ration))
      if @ration.save
      redirect_to @ration
    else
      render :edit
    end
  end

  def create
    @morning = params[:morning][:product_ids]
    @afternoon = params[:afternoon][:product_ids]
    @lunch = params[:lunch][:product_ids]
    @evening = params[:evening][:product_ids]
    if params[:new_ration].blank?
      @new_ration = []
    else
      @new_ration = params[:new_ration][:product_ids]
    end
    @ration = Ration.new(rations_params.merge(morning: @morning, afternoon: @afternoon, lunch: @lunch, evening: @evening, new_ration: @new_ration  ))
    if @ration.save
      redirect_to @ration
    else
      render :new
    end
  end
  def index
    @rations = Ration.all.paginate(page: params[:page], per_page: 5)
  end
  def destroy
    @ration.destroy
    redirect_to rations_path
  end

  def add_to
    render layout: false
  end
  def delete
    
  end

  private

    def rations_params
      params.require(:ration).permit(:name, :description)
    end


    def find_ration
      @ration = Ration.find(params[:id])
    end

    def find_product(product_id)
      Product.where(id: product_id).to_a
    end
end

app/helpers/rations_helper.rb
module RationsHelper
end

app/views/rations/_form.html.erb
<div class="row">
<%=  simple_nested_form_for ration, :html => { :multipart => true } do |f| %>


<div class="col-md-10">

  <%= f.error_notification %>
  <%= f.input :name, label: "Название рациона" %>
  <%= f.input :description, label: "Подробное описание" %>

<div class="rations">
 <div class= 'lol'>
  <div class="col-md-4">
 <div class="test">
  <h4>Продукты на завтрак:</h4>
   <%= collection_check_boxes(:morning, :product_ids, Product.all, :id, :name)do |b| %>
    <div class="row">
      <%= b.label(class: "check_box") do %>
        <div class="col-xs-8">
          <%= b.check_box(class: "check_box") %>
        </div>

        <div class="col-xs-10">
          <%= b.object.name %>
        </div>       
      <% end %>
    </div>
  <% end %>
  </div>
  </div>
</div>
 <div class= 'lol'>
  <div class="col-md-4">
  <div class="test">
  <h4>Продукты на обед:</h4>
   <%= collection_check_boxes(:afternoon, :product_ids, Product.all, :id, :name) do |b| %>
    <div class="row">
      <%= b.label(class: "check_box") do %>
        <div class="col-xs-8">
          <%= b.check_box(class: "check_box") %>
        </div>

        <div class="col-xs-10">
          <%= b.object.name %>
        </div>       
      <% end %>
    </div>
  <% end %>
  </div>
  </div>
  </div>
   <div class= 'lol'>
   <div class="col-md-4">
   <div class="test">
  <h4>Продукты на полудник:</h4>
   <%= collection_check_boxes(:lunch, :product_ids, Product.all, :id, :name)do |b| %>
   <div class="row">
      <%= b.label(class: "check_box") do %>
        <div class="col-xs-8">
          <%= b.check_box(class: "check_box") %>
        </div>

        <div class="col-xs-10">
          <%= b.object.name %>
          
        </div>       
      <% end %>
    </div>
  <% end %>
  </div>
  </div>
  </div>
   <div class= 'lol'>
  <div class="col-md-4">
  <div class="test">
  <h4>Продукты на ужин:</h4>
   <%= collection_check_boxes(:evening, :product_ids, Product.all, :id, :name)do |b| %>
    <div class="row">
      <%= b.label(class: "check_box") do %>
        <div class="col-xs-8">
          <%= b.check_box(class: "check_box") %>
        </div>

        <div class="col-xs-10">
          <%= b.object.name %>
        </div>       
      <% end %>
    </div>
  <% end %>
  </div>
</div>
</div>
</div>
</div>



<div class="col-md-2">
<div class="inter">


 <div><%= f.button :submit, "Создать Рацион", :class => 'btn btn-success btn-block' %></div><br>

  <div><%= link_to 'Добавить прием', '/add_to', id: 'ration', remote: true, class: 'btn btn-success btn-block' %></div><br>
<div><%= link_to 'Удалить прием', '/delete', id: 'ration-delete', method: :delete, remote: true, class: 'btn btn-danger btn-block' %></div>

</div> 
</div>
<% end %>
</div>

app/views/rations/add_to.html.erb
 <div class= 'lol'>
 <div class="col-md-4">
 <div class="test">
  <h4>Продукты на дополнительный прием</h4>
   <%= collection_check_boxes(:new_ration, :product_ids, Product.all, :id, :name)do |b| %>
    <div class="row">
      <%= b.label(class: "check_box") do %>
        <div class="col-xs-8">
          <%= b.check_box(class: "check_box") %>
        </div>

        <div class="col-xs-10">
          <%= b.object.name %>
        </div>       
      <% end %>
    </div>
  <% end %>

  </div>
  </div>
</div>
 

app/views/rations/edit.html.erb
<%= render "form", ration: @ration %>

app/views/rations/index.html.erb
<table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Название</th>
        <th>Описание</th>
        <th>Просмотр. удаление,<br>
        Редактирование</th>
  
      </tr>
    </thead>
  <tbody>
  <% @rations.each do |f| %>
    <tr>
      <td><h4><%= f.name %></h4></td>
      <td><h4><%= f.description%></h4></td>
      <td><%= link_to  f, class: "btn btn-info" do %>
      <i class="glyphicon glyphicon-eye-open"></i>
      <% end %>
       <%= link_to  edit_ration_path(f), class: "btn btn-warning" do %>
      <i class="glyphicon glyphicon-pencil"></i>
      <% end %>
     <%= link_to f, method: :delete, class: "btn btn-danger" do %>
      <i class="glyphicon glyphicon-remove-circle"></i>
      <% end %></td></td>
    </tr>
  </tbody>
<% end %>
</table>
<div class="container text-center">
  <div class="pagination">
    <%= will_paginate @rations, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/rations/new.html.erb
<%= render "form", ration: @ration %>

app/views/rations/show.html.erb
<div class="col-md-12">
    <h2>Название: <%= @ration.name %> </h2>
    <h4>Описание:<br><%= @ration.description %> </h4>
  
    <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th><h4>На завтрак</h4></th>
        <th><h4>На обед</h4></th>
        <th><h4>Перекус</h4></th>
        <th><h4>На ужин</h4></th>
        <th><h4>Дополнительный приемы:</h4></th>
      </tr>
    </thead>
  <tbody>
    <tr>
    <td>
    <% @morning.each do |a| %>
      <h4><%= link_to "#{a.name}", a%></h4>
    <% end %> 
    </td>

    <td>
    <% @afternoon.each do |a| %>
      <h4><%= link_to "#{a.name}", a %></h4>
    <% end %> 
    </td>
    
    <td>
    <% @lunch.each do |a| %>
      <h4><%= link_to "#{a.name}", a %></h4>
    <% end %> 
   </td>
   
   <td>
    <% @evening.each do |a| %>
      <h4><%= link_to "#{a.name}", a %></h4>
    <% end %> 
  </td>
  <td>
    <% @new_ration.each do |a| %>
      <h4><%= link_to "#{a.name}", a %></h4>
    <% end %> 
  </td>
  </tr>
  </tbody>
</table>
</div>