config/routes.rb
Rails.application.routes.draw do
  resources :process_trainings
  resources :trainings
  resources :exercises
  devise_for :users
  devise_for :coaches
  resources :users, :coaches, only: [:show, :edit, :update, :index] do
    get 'chart', on: :member
    get 'dasboards', on: :collection
    get 'statistics', on: :member

    resources :personal_characteristics
  end
  resources :groups do
    resources :schedules

  end
  resources :products
  resources :rations 
 
  get 'add_to' => 'rations#add_to'
  delete 'delete' => 'rations#delete'
  get 'add_to/training' => 'trainings#add_to'
  delete 'delete/training' => 'trainings#delete'
  root 'static_pages#home'
 


  
  get "hello" => "static_pages#dasboard"
  

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :rations
  has_many :attachments, as: :attachmentable

  validates :name, :emulcifying_value, :protein, :carbohydrates, :fats, :portion, presence: true

  accepts_nested_attributes_for :attachments
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :destroy, :edit, :update]

  def new 
    @product = Product.new
  end 

  def show
  end

  def etit
    
  end

  def update
    @product.update(product_params)
      if @product.save
      redirect_to @product
    else
      render :edit
    end
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end
  def index
    @products = Product.all.paginate(page: params[:page], per_page: 5)
  end
  def destroy
    @product.destroy
    redirect_to products_path
  end

  private

    def product_params
      params.require(:product).permit(:name, :emulcifying_value, :protein, :carbohydrates, :fats, :portion, ration_ids: [], attachments_attributes: [:file])
    end


    def find_product
      @product = Product.find(params[:id])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%=  simple_nested_form_for product, :html => { :multipart => true } do |f| %>
<div class="col-md-8 col-md-offset-2">
  <%= f.error_notification %>
  <%= f.input :name, label: "Название продукта" %>
  <%= f.input :emulcifying_value, label: "Енергитическая (Kкал)" %>
  <%= f.input :protein, label: "Белков/100гр" %>
  <%= f.input :carbohydrates, label: "Углеводов/100гр" %>
  <%= f.input :fats, label: "Жиров/100гр" %>
  <%= f.input :portion, label: "Порция(грамм)" %>
  <%= f.fields_for :photos, product.attachments.build do |a| %>
    <%=  a.file_field :file, multiple: true, name: "product[attachments_attributes][][file]" %>
   <% end %><br>
  

  <%= f.button :submit, "Создать продукт", :class => 'btn-custom2' %>
</div>
<% end %>

app/views/products/edit.html.erb
<%= render "form", product: @product %>

app/views/products/index.html.erb
<table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Изображение</th>
        <th>Название</th>
        <th>Енергетическая ценность/100гр</th>
        <th>Кол-во белка/100гр</th>
        <th>Кол-во углеводов/100гр</th>
        <th>Кол-во жиров/100гр</th>
        <th>Просмотр продукта</th>
        <th>Редактирования продукта</th>
        <th>Удаление продукта</th>
      </tr>
    </thead>
  <tbody>
  <% @products.each do |f| %>
    <tr>
      <td><h4><%= image_tag f.attachments.first.file.url.to_s, class: "photo1" %></h4></td>
      <td><h4><%= f.name %></h4></td>
      <td><h4><%= f.emulcifying_value%></h4></td>
      <td><h4><%= f.protein%></h4></td>
      <td><h4><%= f.carbohydrates%></h4></td>
      <td><h4><%= f.fats%></h4></td>
      <td><%= link_to "Просмотреть продукт", f, class: "btn btn-info" %></td>
      <td><%= link_to "Редактирования продукта", edit_product_path(f), class: "btn btn-warning" %></td>
      <td><%= button_to "Удалить продукт", f, method: :delete, class: "btn btn-danger" %></td>
    </tr>
  </tbody>
<% end %>
</table>
<div class="container text-center">
  <div class="pagination">
    <%= will_paginate @products, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/products/new.html.erb
<%= render "form", product: @product %>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-5">
    <% unless @product.attachments.blank? %>
      <%= image_tag @product.attachments.first.file.url.to_s, class: "product-show" %>
        <% @product.attachments.each do |p| %>
          <a href="/products/<%= @product.id %>">
          <%= image_tag p.file.url.to_s, class: "photo" %>
          </a>
        <% end %>
    <% end %> 
  </div>
   <div class="col-md-7">
    <div class="product-info">
      <h2>Название: <%= @product.name %> </h2>
      <h3>Описание продукта:(100гр) </h3><br>
      <h4>Енергетическая ценность<br><%= @product.emulcifying_value%>ккал </h4>
      <h4>Белков: <br><%= @product.protein%>г </h4>
      <h4>Углеводов: <br><%= @product.carbohydrates%>г</h4>
      <h4>Жиров: <br><%= @product.fats%>г</h4><br>
       <h4>Группы рационов в которых находится данный продукт: </h4>
       <% @product.rations.each do |f|%> 
        <h4><%= link_to "#{f.name}", f %></h4>
    <% end %>
    </div>
    </div>
  </div>
  </div>